### ISSUE TITLE
Some files missing based on readme

### ISSUE THREAD

**Issue by pandeydeep9** [HongsinLee/FLAIR#1]
Great work in making the codes publicly available.

Some shell files and requirement files are missing.

For eg. No file cifar10.sh to run bash cifar10.sh. Similarly no requirements.txt file.

**Comment by HongsinLee** [comment]
Hi @pandeydeep9,

Thank you for pointing this out and for your interest in the project! I have now uploaded the missing files.

Please let me know if you encounter any other issues or if something is unclear. Your feedback is greatly appreciated!

**Comment by pandeydeep9** [comment]
Thank you for quick reply and uploading the missing files!! Greatly appreciated :)

Sure, I'm working on a similar project and I plan to include this work as a baseline. Sure will let you know if I run into some issues or confusion.

Best,
Deep
